id: ICAAD2993
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:07.753491
last_modified: 2023-01-04 11:32:07.753504
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  53A6:
    title: The Aspiration of the Vajradhātu Maṇḍala
    base_file: 53A6.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
